services:
  container1:
    image: mysql
    container_name: sql_joins_container
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    ports:
      - 15000:3306
    volumes:
      - ~/project:/var/lib/mysql